apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-pwqm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/mbasti-test-org/happy-depl-cyrc-tenant/appstudio/dc-metro-map-pwqm@sha256:a69923fd0f2307427e90f40ba43d9c7697e44668a87d88bed3d32621a927d088
        name: my-nodejs
        resources: {}
status: {}
