apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-pwqm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-pwqm
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-pwqm
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-pwqm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-pwqm
    spec:
      containers:
      - image: quay.io/mbasti-test-org/happy-depl-cyrc-tenant/appstudio/dc-metro-map-pwqm@sha256:a69923fd0f2307427e90f40ba43d9c7697e44668a87d88bed3d32621a927d088
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
